searchEngines:
  - name: "Google"
    url: "https://www.google.com/search?q=%s&nomo=1"
  - name: "Bing"
    url: "https://www.bing.com/search?q=%s"
  - name: "DuckDuckGo"
    url: "https://duckduckgo.com/?q=%s"
  - name: "雪球"
    url: "https://xueqiu.com/k?q=%s"
  - name: "kimi"
    url: "https://kimi.moonshot.cn/_prefill_chat?prefill_prompt=%s&send_immediately=true&force_search=false"
  - name: "秘塔"
    url: "https://metaso.cn/?q=%s"
  

favoriteSites:
  - name: "browser history"
    url: "chrome://history/"
  - name: "browser bookmarks"
    url: "chrome://bookmarks/"
  - name: "YouTube"
    url: "https://www.youtube.com"
  - type: "folder"
    name: "AI 工具"
    expanded: true
    items:
      - name: "ChandlerAi"
        url: "https://mychandler.bet/chat"
      - name: "Kimi"
        url: "https://kimi.moonshot.cn/"
  - type: "folder"
    name: 新聞資訊
    items:
      - name: Folo
        url: "https://app.follow.is/"
      - type: "folder"
        name: "財經"
        items:
          - name: "雪球"
            url: "https://xueqiu.com/"